apiVersion: batch/v1
kind: CronJob
metadata:
  name: apps-scheduler
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: apps-scheduler-image
            image: busybox
            args:
              - /bin/sh
              - -c
              - date; echo "Hello from cronjob!"
          restartPolicy: Never
