apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apps
  namespace: default
spec:
  encryptedData:
    VERSION: AgC48fYazy3eWj2mJmsZ3KdWYxUsSeKY9yAoHSpZPjLoXAlcs7J5NQNgfWcPjRCIq11PO5rxpsk5wvFw84DRDel/CftxHMuhWi342Zhoo6rGciHNj10fl1eFhS0vdZX8/405eDVFaZyrzUQ7rE7aGrLW1j27B/PRRjXtTXIq+ng35ErHMVoDWxUq39cavQ5Mnn2zCq8Z6XxTslpinfDrRGB9Hf2T82s0bN1hst3ak3lJnP6a7Gf3QymB8W1MwJFfFrjoVk6nLl5WINwiQM4UVDbNfl0VH9/9B9LAEF4rah4gsgXzYOyWRfBQ6Lkz6Brc7aVW7mSD1+FwJYmr4osjZQtyiAtlFXyprbkpZEpwMoN7JwFhWocrVKZQqKCesNQvajn5+p6c3gzoAPfk/tCo1alMSFYB7qLFY8XCOxuwC57zdliK2BCPoYssbAmD1n18v6OrSbMpvz90UXtMCrR0YKVQKNLtuXfDtCWB8SHFOfEMQnh2s0iR1EyELbEFY+e2GBfB0KTfSz0aDOmhEJHTeOPAYvPFNklqa589zsEA4LuVnY91ZivmQ8MYXyzFs9NzyB/M04IJb3IPn47izd61Gn+ni90OIhoXZIrnXbnXImE6/wQHZjW92csm7QBR1GMqyv9mN8tD9lwB8AbEcqma9qtOUNUf4DIeBZJG20XTZcA7Hy9bDidFtdnYuJKIl1JAERNpiITM3w==
  template:
    metadata:
      name: apps
      namespace: default